import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def render():
    spec = json.loads((ROOT / "docs/contracts/diagnostics.openapi.json").read_text())
    lines = [
        "# Foundation API contracts",
        "",
        "Generated by tools/generate_api_docs.py; do not edit.",
        "",
        "Runtime HTTP: GET /healthz. Other contracts are foundation diagnostics.",
        "",
    ]
    for name, schema in spec["components"]["schemas"].items():
        lines.extend([f"## {name}", "", "```json", json.dumps(schema, indent=2), "```", ""])
    runtime = json.loads((ROOT / "docs/contracts/runtime.openapi.json").read_text())
    lines.extend(["## Runtime OpenAPI", "", "```json", json.dumps(runtime, indent=2), "```", ""])
    chat = json.loads((ROOT / "docs/contracts/chat.openapi.json").read_text())
    lines.extend(["## Chat OpenAPI", "", "```json", json.dumps(chat, indent=2), "```", ""])
    return "\n".join(lines)


if __name__ == "__main__":
    (ROOT / "docs/api.md").write_text(render(), encoding="utf-8")
