import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def render():
    spec = json.loads((ROOT / "docs/contracts/diagnostics.openapi.json").read_text())
    lines = [
        "# Foundation API contracts",
        "",
        "Generated by tools/generate_api_docs.py; do not edit.",
        "",
        "No HTTP endpoints implemented yet. These schemas define the current data contracts.",
        "",
    ]
    for name, schema in spec["components"]["schemas"].items():
        lines.extend([f"## {name}", "", "```json", json.dumps(schema, indent=2), "```", ""])
    return "\n".join(lines)


if __name__ == "__main__":
    (ROOT / "docs/api.md").write_text(render(), encoding="utf-8")
